language = "Javascript"
version = "18.12.1"
compiled = false
extension = "js"
environment = [ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/node/18.12.1/bin"]
build_command = []
run_command = [ "/opt/node/18.12.1/bin/node", "{file}" ]
test_file = "test.js"
aliases = ["javascript", "js"]
should_limit_memory = true
memory_limit = 512
process_limit = 512
allowed_entrypoints = 1
