language = "C++"
version = "10.2.1"
compiled = true
extension = "cpp"
build_command = [
    "g++",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-O2",
    "-std=c++17",
    "-pedantic",
    "-o",
    "code",
    "{file}"
]
environment = []
run_command = [ "./code" ]
test_file = "test.cpp"
aliases = ["c++", "cpp"]
should_limit_memory = true
memory_limit = 256
process_limit = 256
