language = "Brainfuck"
version = "2.7.3"
compiled = false
extension = "bf"
build_command = []
environment = []
run_command = [ "/opt/brainfuck/2.7.3/usr/local/bin/brainfuck", "{file}" ]
test_file = "test.bf"
aliases = ["brainfuck", "bf"]
should_limit_memory = true
memory_limit = 256
process_limit = 256
