language = "Go"
version = "1.21.4"
compiled = true
extension = "go"
build_command = [ "/opt/go/1.21/go/bin/go", "build", "-o", "code", "{file}"]
run_command = [ "./code" ]
test_file = "test.go"
environment = [ "GOPATH=/opt/go/1.21/go", "PATH=/opt/go/1.21/go/bin" ]
aliases = [ "go", "golang" ]
should_limit_memory = false
memory_limit = 0
process_limit = 4096
allowed_entrypoints = -1
