language = "Python"
version = "3.12.0"
compiled = false
extension = "py"
environment = [ "PATH=/opt/python/3.12.0/bin" ]
build_command = []
run_command = [ "/opt/python/3.12.0/bin/python3", "{file}" ]
test_file = "test.py"
aliases = ["python", "py"]
should_limit_memory = true
memory_limit = 256
process_limit = 256
allowed_entrypoints = 1
